apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: prometheus-example-app
  name: example-app
  namespace: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: weedesigners/example-app:latest
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 8080
        resources:
          limits:
            cpu: 0.1
            memory: 1Gi
