apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hermes.service.name }}
  namespace: {{ .Values.hermes.namespace }}
spec:
  selector:
    app: {{ .Values.hermes.app.name }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.hermes.service.port }}
      targetPort: {{ .Values.hermes.container.port }}
