apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: mysql
spec:
  storageClassName: mysql-manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi