apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.themis_executor.service_account }}
  namespace: {{ .Values.themis_executor.namespace }}
  labels:
    app: {{ .Values.themis_executor.app_name }}
    name: {{ .Values.themis_executor.service_account }}
