apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.themis_executor.service.name }}
  namespace: {{ .Values.themis_executor.namespace }}
spec:
  selector:
    app: {{ .Values.themis_executor.app_name }}
  type: NodePort
  ports:
    - protocol: "TCP"
      port: {{ .Values.themis_executor.service.port }}
      targetPort: {{ .Values.themis_executor.container_port }}
      nodePort: {{ .Values.themis_executor.service.node_port }}
