apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.hephaestus.persistent_volume }}
spec:
  storageClassName: {{ .Values.hephaestus.storage_class_name }}
  capacity:
    storage: 25Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/hephaestus-gui-pv"