hephaestus:
  namespace: hephaestus
  app_name: hephaestus-gui
  persistent_volume: hephaestus-gui-pv
  persistent_volume_claim: hephaestus-gui-pvc
  storage_class_name: hephaestus-manual
  deplyoment: hephaestus-gui-deployment
  container:
    name: hephaestus-gui
    image: hephaestusmetrics/gui:latest
    port: 8080
  image_pull_policy: Always
  service:
    name: hephaestus-gui-svc
    port: 8080
    node_port: 31122

prometheus:
  namespace: monitoring
  service:
    name: monitoring-kube-prometheus-prometheus
    port: 9090
